### ISSUE TITLE
Cannot find module './cookie-consent-banner.entry.js'

### ISSUE THREAD

**Issue by switchnollie** [porscheofficial/cookie-consent-banner#6]
**Node/npm version(s)**:
v16.13.0

**Package(s) version(s)**:

```
    @porscheofficial/cookie-consent-banner@2.1.3
    @porscheofficial/cookie-consent-banner-react@2.1.3
```

**Browser(s) version(s)**:
Chrome 100.0.4896.127

**Description of the issue/feature**:
Component is not rendered and the stack trace shows:

```
Uncaught (in promise) Error: Cannot find module './cookie-consent-banner.entry.js'
    at newRequire (index.2d3ace14.js:61:19)
    at newRequire (index.2d3ace14.js:45:18)
    at localRequire (index.2d3ace14.js:84:35)
    at loadModule (index-6c3638be.js:1108:12)
    at initializeComponent (index-6c3638be.js:869:20)
    at connectedCallback (index-6c3638be.js:964:17)
    at index-6c3638be.js:1044:39
    at Object.jmp (index-6c3638be.js:12:17)
    at HostElement.connectedCallback (index-6c3638be.js:1044:29)
    at appendChildToContainer (react-dom.development.js:11040:16)
```

**Comment by ppuritscher** [comment]
Hi @switchnollie!

Is it possible that you provide a Codesandbox to reproduce this issue?
